spring:
  config:
    import: optional:file:.env[.properties]
  messages:
    basename: messages, errors
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
logging:
  level:
    #logger出力で利用
    org.hibernate.SQL: debug
